version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/file
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_JPA_GENERATE_DDL: true

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: file
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
